version: '3'
services: 
    node:
        container_name: node-api
        build: ./API
        ports: 
            - '81:3000'
        links: 
            - mongo 
    mongo:
        container_name: mongo
        build: ./DB
        ports: 
            - '27017:27017'
    website:
        container_name: apache
        build: ./WebApp
        ports:
            - '8080:80'
